### ISSUE TITLE
Tapping the preview area a few times causes autofocus force close for me 100%

### ISSUE THREAD

**Issue by jdeltoft** [Wrdlbrnft/BetterBarcodes#6]
2018-11-18 00:12:23.895 11729-11729/com.ideal.Audacy E/Camera: Error 2
2018-11-18 00:12:23.905 11729-11729/com.ideal.Audacy E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ideal.Audacy, PID: 11729
    java.lang.RuntimeException: autoFocus failed
        at android.hardware.Camera.native_autoFocus(Native Method)
        at android.hardware.Camera.autoFocus(Camera.java:1312)
        at com.github.wrdlbrnft.betterbarcodes.reader.a.a$3.run(Unknown Source:28)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6665)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)

**Comment by jdeltoft** [comment]
Ok, I made the framelayout above this barcode reader preview as clickable with android:clickable="true" and that prevents touch input to trigger auto focus.

**Comment by phanidatta** [comment]
I am using barcode  scanning for my Android app!!
barcode length is 22 character long with alphanumeric (DPC-SL-M006A-FP09-CKT3-PL970). problem is scanning is too slow and it will scan 1 time out of 10 times.
is there any character limitations for barcode? there is no issues with numeric barcode scans.
