### ISSUE TITLE
NPE happened

### ISSUE THREAD

**Issue by alanlai1989** [Wrdlbrnft/BetterBarcodes#7]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
       at com.github.wrdlbrnft.betterbarcodes.reader.base.a.a(Unknown Source)
       at com.github.wrdlbrnft.betterbarcodes.reader.a.a.a(Unknown Source)
       at com.github.wrdlbrnft.betterbarcodes.reader.a.b.onPreviewFrame(Unknown Source)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1272)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5839)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

**Comment by alanlai1989** [comment]
@Wrdlbrnft
