### ISSUE TITLE
Fail to connect to camera service

### ISSUE THREAD

**Issue by alanlai1989** [Wrdlbrnft/BetterBarcodes#8]
```
Fatal Exception: java.lang.RuntimeException: Fail to connect to camera service
       at android.hardware.Camera.(Camera.java:653)
       at android.hardware.Camera.open(Camera.java:512)
       at com.github.wrdlbrnft.betterbarcodes.reader.a.a.a(Unknown Source)
       at com.github.wrdlbrnft.betterbarcodes.reader.a.a.a(Unknown Source)
       at com.github.wrdlbrnft.betterbarcodes.reader.base.a.startPreview(Unknown Source)
       at com.github.wrdlbrnft.betterbarcodes.views.reader.BarcodeReaderView.start(Unknown Source)
       at com.kfit.fave.fragment.QRScannerFragment.onResume(QRScannerFragment.java:132)
       at android.support.v4.app.Fragment.performResume(Fragment.java:2390)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1474)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3212)
       at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:217)
       at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
       at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
       at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
       at android.app.Activity.performResume(Activity.java:6276)
       at android.app.ActivityThread.performNewIntents(ActivityThread.java:2772)
       at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2779)
       at android.app.ActivityThread.access$1700(ActivityThread.java:188)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1602)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5839)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
```
This cause only happen on Android 4.4 and 5. Above those version, it was fine

**Comment by alanlai1989** [comment]
@Wrdlbrnft any idea?
